export const pieceIssuerNFTAbi = {
    "network": "bsc_testnet",
    "contract": {
      "address": "0x920430F6976E1dcd90d11822c14F1CE0508ebafd",
      "signerAddress": "0x8C42A81Aa4C05212668b3064D7bd8b8e52Cf3b06",
      "abi": [
        "event AddOperator(address indexed operator, address indexed sender, uint256 timestamp)",
        "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
        "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
        "event Initialize(address indexed owner, string name, string symbol, uint256 timestamp)",
        "event Initialized(uint8 version)",
        "event IssuerAccepted(address indexed issuer, address indexed operator, uint256 timestamp)",
        "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
        "event Paused(address account)",
        "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
        "event Unpaused(address account)",
        "function PIECE_BEACON() view returns (address)",
        "function acceptIssuer(address issuer, address operator)",
        "function addOperator(address operator, tuple(string name, string country, string metadataUri) operatorData)",
        "function applyAsIssuer(address sender, tuple(string name, address operator, string metadataURI) data)",
        "function approve(address, uint256) pure",
        "function balanceOf(address owner) view returns (uint256)",
        "function burn(uint256 tokenId)",
        "function createIssuerProfile(address sender, string metadataURI) returns (uint256)",
        "function getApplication(address applicant) view returns (tuple(string name, address operator, string metadataURI))",
        "function getApproved(uint256 tokenId) view returns (address)",
        "function getOperator(address operator) view returns (tuple(string name, string country, string metadataUri))",
        "function getOwnedPetProfiles(address owner) view returns (uint256[])",
        "function initialize(address pieceBeacon, address owner, string name, string symbol)",
        "function isApprovedForAll(address owner, address operator) view returns (bool)",
        "function name() view returns (string)",
        "function owner() view returns (address)",
        "function ownerOf(uint256 tokenId) view returns (address)",
        "function pause(bool toPause)",
        "function paused() view returns (bool)",
        "function registerPiece(tuple(uint256 issuerId, string name, string symbol, string pieceTokenURI, bool shouldDeploy) data)",
        "function renounceOwnership()",
        "function safeTransferFrom(address, address, uint256) pure",
        "function safeTransferFrom(address, address, uint256, bytes) pure",
        "function setApprovalForAll(address, bool) pure",
        "function supportsInterface(bytes4 interfaceId) view returns (bool)",
        "function symbol() view returns (string)",
        "function tokenURI(uint256 tokenId) view returns (string)",
        "function totalBurned() view returns (uint256)",
        "function totalMinted() view returns (uint256)",
        "function totalSupply() view returns (uint256)",
        "function transferFrom(address, address, uint256) pure",
        "function transferOwnership(address newOwner)"
      ]
    }
  }